#!/usr/bin/env bash
# Mint a fresh service-account token against the local Grafana and write
# it to integration/.integration-env. Idempotent: if the service account
# already exists, deletes its old tokens and mints a new one (tokens
# can't be read back after creation, so rotation is the only sane path).
#
# Admin basic-auth credentials come from the docker-compose env. The
# token, not the admin password, is the secret — the env file is mode
# 0600 and gitignored.

set -euo pipefail

GRAFANA_URL="${GRAFANA_URL:-http://localhost:3000}"
ADMIN_USER="${GRAFANA_ADMIN_USER:-admin}"
ADMIN_PASS="${GRAFANA_ADMIN_PASS:-admin}"
SA_NAME="${SA_NAME:-mobile-viewer}"
SA_ROLE="${SA_ROLE:-Viewer}"
TOKEN_NAME="${TOKEN_NAME:-dev-token}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/../.integration-env"

auth=(-u "$ADMIN_USER:$ADMIN_PASS")
ct=(-H "Content-Type: application/json")

# 1. Find or create the service account.
existing=$(curl --silent "${auth[@]}" \
  "$GRAFANA_URL/api/serviceaccounts/search?query=$SA_NAME")
sa_id=$(printf '%s' "$existing" \
  | sed -n 's/.*"id":\([0-9][0-9]*\),"name":"'"$SA_NAME"'".*/\1/p' \
  | head -n1)

if [ -z "$sa_id" ]; then
  create_resp=$(curl --silent --fail "${auth[@]}" "${ct[@]}" \
    -d "{\"name\":\"$SA_NAME\",\"role\":\"$SA_ROLE\",\"isDisabled\":false}" \
    "$GRAFANA_URL/api/serviceaccounts")
  sa_id=$(printf '%s' "$create_resp" \
    | sed -n 's/.*"id":\([0-9][0-9]*\).*/\1/p' | head -n1)
  if [ -z "$sa_id" ]; then
    printf "ERROR: could not parse service-account id from: %s\n" "$create_resp" >&2
    exit 1
  fi
  printf "Created service account %s (id=%s, role=%s)\n" "$SA_NAME" "$sa_id" "$SA_ROLE"
else
  printf "Reusing service account %s (id=%s)\n" "$SA_NAME" "$sa_id"
  # Delete existing tokens — we cannot read their values back.
  token_ids=$(curl --silent "${auth[@]}" \
    "$GRAFANA_URL/api/serviceaccounts/$sa_id/tokens" \
    | sed -n 's/.*"id":\([0-9][0-9]*\)[,}].*/\1/gp')
  for tid in $token_ids; do
    curl --silent --fail "${auth[@]}" -X DELETE \
      "$GRAFANA_URL/api/serviceaccounts/$sa_id/tokens/$tid" > /dev/null
  done
fi

# 2. Mint a fresh token.
token_resp=$(curl --silent --fail "${auth[@]}" "${ct[@]}" \
  -d "{\"name\":\"$TOKEN_NAME-$(date +%s)\"}" \
  "$GRAFANA_URL/api/serviceaccounts/$sa_id/tokens")
token_key=$(printf '%s' "$token_resp" \
  | sed -n 's/.*"key":"\([^"]*\)".*/\1/p')

if [ -z "$token_key" ]; then
  printf "ERROR: could not parse token key from: %s\n" "$token_resp" >&2
  exit 1
fi

# 3. Persist to .integration-env (mode 0600).
umask 077
cat > "$ENV_FILE" <<EOF
# Generated by integration/scripts/bootstrap-token.sh — do not commit.
GRAFANA_URL=$GRAFANA_URL
GRAFANA_TOKEN=$token_key
EOF

printf "Wrote %s\n" "$ENV_FILE"
printf "\nPaste into the app:\n  Server URL: %s\n  Token:      %s\n" \
  "$GRAFANA_URL" "$token_key"
